⚠️ 目標已存在: /home/aronton/tSDRG_random/tSDRG/Main_15/data_random/PBC/Jdis060/Dim041
✅ 已成功複製:
/homeold/aronton/tSDRG_random/tSDRG/Main_15/data_random/PBC/Jdis060/Dim042
→
/home/aronton/tSDRG_random/tSDRG/Main_15/data_random/PBC/Jdis060/Dim042
⚠️ 目標已存在: /home/aronton/tSDRG_random/tSDRG/Main_15/data_random/PBC/Jdis060/Dim043
✅ 已成功複製:
/homeold/aronton/tSDRG_random/tSDRG/Main_15/data_random/PBC/Jdis060/Dim044
→
/home/aronton/tSDRG_random/tSDRG/Main_15/data_random/PBC/Jdis060/Dim044
⚠️ 目標已存在: /home/aronton/tSDRG_random/tSDRG/Main_15/data_random/PBC/Jdis060/Dim045
✅ 已成功複製:
/homeold/aronton/tSDRG_random/tSDRG/Main_15/data_random/PBC/Jdis060/Dim046
→
/home/aronton/tSDRG_random/tSDRG/Main_15/data_random/PBC/Jdis060/Dim046
✅ 已成功複製:
/homeold/aronton/tSDRG_random/tSDRG/Main_15/data_random/PBC/Jdis060/Dim047
→
/home/aronton/tSDRG_random/tSDRG/Main_15/data_random/PBC/Jdis060/Dim047
✅ 已成功複製:
/homeold/aronton/tSDRG_random/tSDRG/Main_15/data_random/PBC/Jdis060/Dim048
→
/home/aronton/tSDRG_random/tSDRG/Main_15/data_random/PBC/Jdis060/Dim048
✅ 已成功複製:
/homeold/aronton/tSDRG_random/tSDRG/Main_15/data_random/PBC/Jdis060/Dim049
→
/home/aronton/tSDRG_random/tSDRG/Main_15/data_random/PBC/Jdis060/Dim049
✅ 已成功複製:
/homeold/aronton/tSDRG_random/tSDRG/Main_15/data_random/PBC/Jdis060/Dim050
→
/home/aronton/tSDRG_random/tSDRG/Main_15/data_random/PBC/Jdis060/Dim050
Traceback (most recent call last):
  File "/home/aronton/tSDRG_random/Subpy/copy1.py", line 23, in <module>
    shutil.copytree(src, dst)
  File "/home/aronton/anaconda3/lib/python3.12/shutil.py", line 598, in copytree
    with os.scandir(src) as itr:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/homeold/aronton/tSDRG_random/tSDRG/Main_15/data_random/PBC/Jdis060/Dim051'
